# Generated by Django 5.0.4 on 2024-05-23 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Appoinment",
            new_name="Appointment",
        ),
    ]
