# Generated by Django 5.0.4 on 2024-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0004_remove_doctor_name_doctor_user_patient_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
